### ISSUE TITLE
Trying to boot macOS Monterey with legacy option rom enabled

### ISSUE THREAD

**Issue by ytain** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#11]
As per the title of the issue, I'm trying to figure out a way to boot macOS Monterey with the bios setting 'Advanced Boot Options - Untick "Enable Legacy Option ROMs" and "Enable Attempt Legacy Boot" should be greyed out' flipped, cause I need this option enabled to allow the machine to go past the Dell logo screen with the AMD RX 6400 installed on my Optiplex 7050 SFF (I've based the OpenCore setup based from your setup, thank you very much).

I think there's a bug in the Dell BIOS about this interaction between the GPU and that legacy option rom. 

With that bios setting disabled, I can't even get into the bios or boot manager (F2/F12) at all when the gpu card is installed.

I already added the gpu_disable.aml to the opencore to be enforced so the macOS won't even detect the installed GPU.

Do you have any ideas/guesses on how to make the macOS get booted/installed with the legacy option rom setting enabled?

--- Additional info (edit) ---

Yes, the RX6400 GPU card low profile from Sapphire works very well on this machine in Windows/Linux, can play games on it as well.
And the bios is updated to the latest, 1.22.1 . I see there's a new BIOS version out now, gonna try to see if this new update will fix my issue or not.

---

If it doesn't work, then I would have to go thru the hardware passthrough via QEMU (for igpu, etc).

I know that the 'Enable Legacy Option ROMs' is required to help with the setting of CFG Lock variable.

**Comment by linkev** [comment]
Hi @ytain Sorry for the long delay on this reply. Hmm, I also have a Sapphire RX6400, but not the SFF version of the 7050 so can't test out that scenario unfortunately. In the BIOS, I recall a setting that lets you choose either the integrated graphics or the dGPU to take priority, also an Auto option. Maybe playing with that would fix the issues?

If it's playing up in the BIOS then it might be something beyond macOS/Hackintosh itself. The GPU itself is pretty useless for anything else than low-end gaming directly plugged in, it doesn't have the encoder/decoder macOS/Windows uses, other parts missing and I think macOS doesn't even support it natively, when it supports something like the RX 580.

I'd recommend sticking with the integrated iGPU as that's definitely supported, you won't be doing much gaming on macOS anyway 😄
