### ISSUE TITLE
Dell 7050 (regular desktop) kbl 630 GPU not working 

### ISSUE THREAD

**Issue by sdmyers1209** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#12]
GPU not working, weird colors, everything is slow

**Comment by JohnAker33** [comment]
This is only for the Micro versions of the 5050/7050. The UEFI offsets that you have to change the values for are completely different for the 7050 SFF and MT. Those would need to be researched before changing them in your Dell.

**Comment by linkev** [comment]
I might be able to find the offsets for whatever Dell @sdmyers1209 is using if they could provide the BIOS .exe from Dell itself

Thanks for the idea @JohnAker33 they might actually be slightly different

**Comment by sdmyers1209** [comment]
After many other of just playing with it I did get it to work. Though there
are some problems with the IGPU other than that if you have a DGPU your
golden to use this

**Comment by linkev** [comment]
Sounds good, glad it worked out for you in the end 😄
