### ISSUE TITLE
Blank screen no signal on recovery boot at graphics step

### ISSUE THREAD

**Issue by bdpna** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#13]
Thanks for all you have done for this machine!

Optiplex 7050 with an i5, otherwise specs the same.  CFG and BIOS properly set, as well as UEFI variables.

Attempted boot with both display ports and HDMI.  All settings followed and tried with 0.8.7 and 0.9.2 with same result.  Long 2 minute pause on BootKernelExtensions.kc (wake failure) followed by several screens of text (looks like mostly failures) during recovery boot.  Attempting to install Ventura from the 2 recovery files in the proper folder on 8 GB USB stick.  

Apple logo shows for a split second followed by no signal to monitor.  Attempted to switch ports as well (thinking maybe routing video to a different port at this point).

Unsure if kernel panic or just a video issue.  Any tips most appreciated!

**Comment by lorenzoiuri** [comment]
I encountered the same problem. The workaround that worked for me was to unplug and replug the cable a couple of times.

**Comment by linkev** [comment]
Hey @bdpna not sure if you have a dedicated GPU plugged in, but by all means it should be using the iGPU to run everything. I will admit the DeviceProperties section is pretty barebones and if it did work for me, seems like it doesn't work as well for you 😨 

I'd suggest maybe having a glance over https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#deviceproperties again, maybe a BIOS reset and re-setup could help.

HDMI for me personally has given wrong colours, so I just stuck with using DisplayPort and a DP to HDMI adapter to plug in my monitor, whenever I need it, usually it's headless. Sorry I can't be of much help 😢
