### ISSUE TITLE
Skylake CPU

### ISSUE THREAD

**Issue by kymerea** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#14]
This EFI should in theory work with Skylake if some minor things are changed in the config.plist?
I just went through the opencore guide and compares the sections of Kaby Lake (7th gen) and Skylake (6th gen) and noticed one minor difference [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#deviceproperties).
Would there be any changes needed for the GPU to work properly or is there no changes necessary? 

Edit:
Just thought I'd specify, I have an i5 6600 (pretty sure its a T but it may not)

**Comment by linkev** [comment]
Hey @ItxWeird Yep you're right, someone else commented about the Skylake 530 GPU being the culprit, which would make sense and changing the Device Property should fix the GPU related issues. I'll make a note in the readme to let people know you could change a few lines with Opencore Configurator and be good to go, thanks!
