### ISSUE TITLE
[micro] Combo jack microphone not working

### ISSUE THREAD

**Issue by lorenzoiuri** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#15]
Hi all, thank you for these configurations.
I managed to install opencore on an optiplex 3050 micro by replacing only the NIC kext (from the intel to a realtek one).
However, I found that the audio configuration is not correct.
I'm posting it here because, apparently, the 7050 micro and the 3050 micro share the same audio chip (Realtek ALC3234) and have the same audio ports.

The integrated speaker works, the headphone combo works only as an output, the line out doesn't work.

The wiki on the AppleALC kext [doesn't specify a profile](https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC255/Info.plist) for the optiplex micro.

Does someone managed to get the headphone combo work as an input?

Thanks!

**Comment by lorenzoiuri** [comment]
I also noticed that the headphone out is pretty tinny unless the balance is completely right or left.
The internal speaker works fine.

Has anybody experienced this behaviour?

**Comment by linkev** [comment]
@lorenzoiuri Haven't really extensively tested the combo jack since I don't have a headset that could do that. Not sure if you managed to get with this anywhere, pull requests are welcome.

If I ever get a headset that can test it, I'll try to figure it out
