### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by JohnAker33** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#16]
This guide also works for the Dell Optiplex 5050 Micro as long as a Kaby Lake i5/i7 CPU is installed. Might be a good idea to make a note about that. More people can then use the guide and EFI folder.

**Comment by linkev** [comment]
Hey @JohnAker33 Thanks for letting me know. Yeah I should make it more clear, I have noted that somewhere in the readme, but this is mainly for my specific configuration.

Dell Optiplexes are pretty much the same one generation backward and forward, so you're right that it should work, Intel CPU's also didn't change much back then 😄
