### ISSUE TITLE
wont boot into installer

### ISSUE THREAD

**Issue by SaltyPlayzYT** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#17]
hey guys im trying to boot into the macOS Ventura installer and i followed the readme bios variables and changed the smbios and used CFG unlock and i try to boot into installer but then it reboots right after verbose

any help would be appreciated thank you

**Comment by linkev** [comment]
Hey @SaltyPlayzYT Depending on your specs, unless you have the exact same as mine, I can't guarantee anything. You might want to follow the Dortania guide to see if you've missed anything: https://dortania.github.io/OpenCore-Install-Guide/

Usual suspects are WiFi, GPU and wrong BIOS settings. Drive compatibility is also important.
