### ISSUE TITLE
The U disk boot installation of ventura is stuck with the following error and cannot be performed.

### ISSUE THREAD

**Issue by shaodt0716A** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#18]
#[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
#[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
#[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH

PS: CFG Lock 0x00
Bios Also perform normal reference configuration.

I'm still stuck with some bugs and can't proceed further. Please advise and I need to configure before I can continue.

**Comment by linkev** [comment]
Hi @shaodt0716A No sure how I can help out, other than recommending to look through the Dortania guide according to your setup. Not sure what your specs are, but the closer the better. I can suggest removing anything to do with WiFi in the OpenCore config and the computer itself if possible, it has saved me time and helped troubleshoot in the past
