### ISSUE TITLE
Support for the i7 6700?

### ISSUE THREAD

**Issue by realgorgan** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#19]
Hi There,

I've been trying for countless hours to get this EFI working on my 7050M running an i7 6700, I have gotten the device to boot and install Monterey but I have no hardware acceleration, now the iGPU is an HD 530 which I believe is the culprit of this issue. Has anyone had luck installing macOS using this EFI on the i7 6700 (Intel HD 530) version of the 7050M?

**Comment by linkev** [comment]
Hey @FuseBarTV You may need to refer to this part of the guide and modify your device properties. Intel CPU's from that era are similar so the 6700 should work, but you're right that the GPU is a culprit. I'd say try these steps and see if you can get it working: https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#deviceproperties

You might also need to change the SMBIOS if you're trying to run beyond Ventura as it says in the Note 2 comment here: https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#platforminfo
