### ISSUE TITLE
Blinking display

### ISSUE THREAD

**Issue by johnfried** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#2]
Hey amazing work here, thank you! I have this up and installed on a Optiplex 7050 micro with the BCM94360NG Wifi card, and only 8GB of RAM. Its an i5 Kaby Lake, I used BigSur as the install. So this is seems to be speedy and works, but the display will randomly blink off then back on again. Do you have any ideas on this? Thanks in advance

**Comment by johnfried** [comment]
Solved this by disabling USB wake in BIOS

**Comment by linkev** [comment]
Hey @johnfried Thank you for the kind words! Sorry for the late reply, I'm glad you got your issue fixed :) I was going to double check if you set the variables right for DVMT and BIOS settings are correct, but I still haven't uploaded all of my BIOS settings for people to copy. Busy with life, but I'll write those out now so you and people in the future can compare 👍 

Enjoy your hackintosh while Apple still supports Intel!
