### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by kymerea** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#21]
Is there a way of controlling the fans in this EFI? Is there an app of sorts that can do so?

**Comment by linkev** [comment]
Hey @ItxWeird I think I mentioned exelban Stats at the bottom of my readme, you can install its Fan Helper and control it how you like, if your SMC is working properly: https://github.com/exelban/stats

**Comment by jhy-jhy0** [comment]
Macs fan control
