### ISSUE TITLE
no graphics acceleration

### ISSUE THREAD

**Issue by coldi2k3** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#24]
solved. i replaced it with another 7050 and now its working fine

**Comment by linkev** [comment]
Hey @coldi2k3 happy to hear the replacement worked, I was going to suggest resetting/reflashing the BIOS. Could have been the processor itself, but the T models just have a lower TDP, they should still have the same GPU etc. Anyway, glad it's working for you now, enjoy!

**Comment by coldi2k3** [comment]
I have already installed a few hacks. With this one I really doubted myself for a while. I'm glad I had a second optiplex 7050 and it worked straight away. Many thanks again for your great instructions here :)
