### ISSUE TITLE
Can't get to install screen

### ISSUE THREAD

**Issue by SzaboTomek** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#4]
Hi,
maybe i'm dumb but i can't get to install screen.
My 7050 a bit different ( 8gb ram, i5-7500U) but i don't think it's make any difference.
I did everything what is in the tutorial:
- Bios is set up like yours
- changed the Serials (CHANGE ME)
- updated the kexts
- updated OpenCore to 0.7.8
- did the cfg lock stuff (says UNLOCKED in ControlMsrE2.efi)
- even did my own ssdt (did with SSDTTime on linux)
- deleted wifi related boot args and wifi kexts (using original apple wifi card from macbook air) (now i put back intel card)

But i'm stuck on "deferred rematching count 0"
                            
Please help me to make it work! 

![IMG_0688](https://user-images.githubusercontent.com/99558307/153726288-6bb277a1-fb67-47fb-8d0c-253f395629ad.jpg)
<img width="1032" alt="Screenshot 2022-02-12 at 20 45 23" src="https://user-images.githubusercontent.com/99558307/153726298-ac51974f-7255-49e7-9457-2dcb20e8b07e.png">
[config.txt](https://github.com/linkev/Dell-Optiplex-7050-Micro-Hackintosh/files/8054420/config.txt)

**Comment by SzaboTomek** [comment]
Actually, I was dumb. I missed these:
- DVMT Pre-Allocated
- DVMT Total Gfx Mem
- Bi-Directional PROCHOT

After I set up this, i can reach the install screen, however, it was just a gray screen with cursor.
I had to delete the prev-lang:kbd 'Value', and setting the type to 'Data'. After this modification, I installed MacOS Monterey.

I really appreciate this guide, without this, I was completely lost.

Thank you again.

**Comment by linkev** [comment]
Heya @SzaboTomek !

I'm glad you got it figured out, when I was setting this up for the first time, I made the mistake of turning off CPU XD support which stopped me from booting altogether. I spent a good couple of hours troubleshooting it and even bothering other people on Reddit with a similar config, until I realized my stupidity 🤦 

I know its very satisfying when it finally works, so congratulations! Make sure you store that working EFI somewhere safe, you don't want to lose all of this progress 😄
