### ISSUE TITLE
Does the ROM in config.plist need to be changed?

### ISSUE THREAD

**Issue by dongwa** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#5]
Hello, I have some doubts after watching your readme
I am not find `{changme}`,but got this:
`<key>ROM</key>
<data>AAAAAAAA</data>`
so i am not sure if need to change it to my MAC address?

**Comment by linkev** [comment]
Hi, yes you are right, it can be your Ethernet MAC address or a WiFi MAC address.

In the example, I set the MAC address to 00 00 00 00 00 00, which seems to be AAAAAAAA converted. I use OpenCore Configurator to do it which I guess changes depending how you open the config file.

I'll change it to {changeme} the next time I update the repo, sorry about that!
