### ISSUE TITLE
Can macOS update to 12.5?

### ISSUE THREAD

**Issue by thirtykmpersecond** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#6]
Hello! Thanks for your EFI files! Now I'm using it and installed 12.4 on my machine.
Can I update it to 12.5?

**Comment by thirtykmpersecond** [comment]
Fine，It updated to 12.5 automatically ... everything looks ok

**Comment by linkev** [comment]
Hey! Sorry for the late reply, glad the EFI files could help :)
Yeah it should be okay for macOS 12, I'm thinking of going to macOS 13 Beta, but might need to wait until its official and OpenCore has been updated for it.
