### ISSUE TITLE
no display after opencore boot

### ISSUE THREAD

**Issue by xylz0928** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#7]
once select opencore Udisk from F12 menu,
derectly shows black screen (has output, but black)

**Comment by linkev** [comment]
Hey, sorry for the late reply, might be worth trying different display outputs HDMI/DisplayPort, might be something to do with the DVMT allocation, or maybe your Optiplex is different from the Micro version I have. That's all I can think of with what I know, sorry :(
