### ISSUE TITLE
waiting the next repo update for Ventura 

### ISSUE THREAD

**Issue by firstfsx** [linkev/Dell-Optiplex-7050-Micro-Hackintosh#9]
thx

**Comment by linkev** [comment]
Hey, thanks for waiting! Happy to say that the repo is now Ventura ready, enjoy!

**Comment by firstfsx** [comment]
There seems to be something wrong, and it can't boot normally with the latest OC 0.87. Did you upgrade to 13 Ventura online ? Please provide details of the upgrade.
